### ISSUE TITLE
Subchunk1Size: 12smilePcm: bogus wave/riff header or file in wrong format

### ISSUE THREAD

**Issue by WestbrookZero** [Zhangtingyuxuan/AcousticFeatureExtraction#2]
请问你使用的opensmile的版本？我使用opensmile2.3.0最新版本，使用我们场景的音频会报错，报错的解决方案网上查了，请问除了Matlab转换以外能在工程代码里面解决吗？报错如下：
smilePcm: Riff: 46464952
Format: 45564157
Subchunk1ID: 20746d66
Subchunk2ID: 61640000
AudioFormat: 1
Subchunk1Size: 12smilePcm: bogus wave/riff header or file in wrong format ('D:\Projects\Audio\Emotion\SER\AcousticFeatureExtraction\audios/EP03_seq04_sc132.wav')! (maybe you are trying to read a 32-bit wave file which is not yet supported (new header type...)?)

**Comment by zlzhang1124** [comment]
可以先把你的音频转成通用格式，直接通过python中subprocess.run调用ffmpeg工具对音频进行格式转换，比如subprocess.run("ffmpeg -loglevel quiet -y -i %s -acodec pcm_s16le -ac 1 -ar 16000 %s" % (audio_raw, audio_path))，其中audio_raw是你的原始音频，audio_path是转换后音频（调用ffmpeg，将任意格式音频文件转换为.wav文件，pcm有符号16bit,1：单通道,16kHz，不显示打印信息）

**Comment by WestbrookZero** [comment]
已解决，谢谢！
