### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by peak1995** [Zhangtingyuxuan/AcousticFeatureExtraction#3]
你好，想问一下，为什么提出来的特征参数，只有一帧的参数？

**Comment by zlzhang1124** [comment]
检查下音频时长，是否太短（几个ms），小于设定的帧长

**Comment by peak1995** [comment]
必须一帧一帧处理吗？整段语音怎么处理呢？




| |
陈高峰
邮箱：chengaofeng1109@163.com
|

签名由 网易邮箱大师 定制

在2021年01月19日 20:31，ZZL 写道：

检查下音频时长，是否太短（几个ms），小于设定的帧长

**Comment by zlzhang1124** [comment]
> 必须一帧一帧处理吗？整段语音怎么处理呢？ | | 陈高峰 邮箱：chengaofeng1109@163.com | 签名由 网易邮箱大师 定制 在2021年01月19日 20:31，ZZL 写道： 检查下音频时长，是否太短（几个ms），小于设定的帧长 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
这个就是可以处理整句话的，我的意思是，你的音频是否太短（小于两帧），才导致提取到的特征只有一帧

**Comment by peak1995** [comment]
我用的是一句话，但是我发现提出来的只有一帧的语音。




| |
陈高峰
邮箱：chengaofeng1109@163.com
|

签名由 网易邮箱大师 定制

在2021年01月19日 21:01，ZZL 写道：

必须一帧一帧处理吗？整段语音怎么处理呢？ | | 陈高峰 邮箱：chengaofeng1109@163.com | 签名由 网易邮箱大师 定制 在2021年01月19日 20:31，ZZL 写道： 检查下音频时长，是否太短（几个ms），小于设定的帧长 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
这个就是可以处理整句话的，我的意思是，你的音频是否太短（小于两帧），才导致提取到的特征只有一帧

**Comment by zlzhang1124** [comment]
把用的音频发来，还有用的哪个特征提取程序类

**Comment by peak1995** [comment]
为什么输出不是帧数*523维
| |
陈高峰
|
|
chengaofeng1109@163.com
|
签名由网易邮箱大师定制


在2021年01月19日 21:25，ZZL<notifications@github.com> 写道：

把用的音频发来，还有用的哪个特征提取程序类

**Comment by zlzhang1124** [comment]
你用的是程序里的my_acoustic_features方法提取1×523维HSFs特征，这里是HSFs特征，是在LLDs的基础上做一些统计而得到的全局特征，是对utterance上的多帧语音做统计，所以这里肯定是每条语音对应1×523维特征啊，这个方法说明里已经写得很清楚了。

**Comment by peak1995** [comment]
好的，谢谢


| |
陈高峰
|
|
chengaofeng1109@163.com
|
签名由网易邮箱大师定制


在2021年01月20日 09:46，ZZL<notifications@github.com> 写道：

你用的是程序里的my_acoustic_features方法提取1523维HSFs特征，这里是HSFs特征，是在LLDs的基础上做一些统计而得到的全局特征，是对utterance上的多帧语音做统计，所以这里肯定是每条语音对应1523维特征啊，这个方法说明里已经写得很清楚了。
