### ISSUE TITLE
hi，╥﹏╥...

### ISSUE THREAD

**Issue by jun0wanan** [Zhangtingyuxuan/AcousticFeatureExtraction#4]
你好，

  我看了一篇论文，里面说它用
Acoustic: We utilize the toolkit OpenSMILE [13] to extract the
utterance-level features with the configuration of INTERSPEECH2010
[42]. The extracted feature vector is in 1,582 dimension.
不知道你知道open提取的是1582维度的吗？就是是固定的吗

best，
jun

**Comment by zlzhang1124** [comment]
1582维特征就是INTERSPEECH 2010 paralinguistics challenge上的emotion features，可以在OpenSmile中的配置文件里查看（emobase文件），原始配置的特征数就是1582个，你可以通过修改其配置文件来获取你自己想要的特征集。
