### ISSUE TITLE
请教：如何提取带有时序信息的音频特征呢？

### ISSUE THREAD

**Issue by LeMei** [Zhangtingyuxuan/AcousticFeatureExtraction#6]
您好，非常感谢您的工作。请教一下，对于一个.wav的音频文件，应该如何提取出（seq,dim）这样的特征呢，目前我提取的是（dim）,也就说一个音频特征只提取出一个vector，但我想提取出一个矩阵，也就是带帧信息/时序信息的特征，应该用librosa哪一个工具呢？

**Comment by zlzhang1124** [comment]
1.  你可以直接将音频按照20ms左右进行分帧，然后在每一帧上提取声学特征，最后维度结果就是(frame_dim, feature_dim)；
2.  你也可以直接使用相关的软件包，这里推荐openSMILE（python版：https://github.com/audeering/opensmile-python ； C++及命令行版：https://github.com/audeering/opensmile ），利用该工具可以提取一些常用的流行指标，包括低阶帧级别的特征和高阶全局统计特征，如ComParE和eGeMAPS等；
3.  对于你所说的用librosa，其中关于谱的特征，比如MFCC就是类似这样的。

**Comment by LeMei** [comment]
感谢您的回复。相对于这三种音频特征提取工具，是不是第三种更常用。我跑了下MFCC, 对于不同的音频文件，39是不是MFCC个数*3，50，60，211是不是特征维度，为啥每个样本的特征维度不一样，这种情况要进行padding到相同维度？
mfcc_features.shape:(39, 55)
mfcc_features.shape:(39, 60)
mfcc_features.shape:(39, 211)
我在知乎看到一个这样的处理方式
<img width="672" alt="image" src="https://github.com/zlzhang1124/AcousticFeatureExtraction/assets/22788642/69fa755c-541b-4493-935f-d9ad87c37a3d"> 是不是也可以这样操作，分帧，然后提取mel_spectural. 

想问下怎么才能分帧的，https://www.jianshu.com/p/bf6cb803f25e，这个是不是就是分帧后提取mel声谱图的操作。感谢

**Comment by zlzhang1124** [comment]
1. librosa是常用的音频处理工具，通过它可以作后续的各种进一步处理；
2. mfcc_features.shape中的第一维39是梅尔倒谱系数的个数，也就是特征维数，第二维是音频的帧数，其大小取决于音频的长度和处理时的窗长和窗移；
3.  预处理流程大致是这样的，具体的窗长、窗移、滤波器个数等参数看你的应用领域，分帧操作目的就是克服音频的非线性时变问题，用短时平稳这个音频特性进行短时傅里叶变换。

**Comment by LeMei** [comment]
谢谢回复，理解了，感谢
